const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const today = new Date();
const iso = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const monthStart = iso(new Date(today.getFullYear(),today.getMonth(),1));
const fmt = (n,c="TJS") => new Intl.NumberFormat("ru-RU",{style:"currency",currency:c,maximumFractionDigits:2}).format(n);
const currencies = ["TJS","USD","EUR","RUB"];
const categories = {
 expense:["Обед","Продукты","Транспорт","Дом","Здоровье","Покупки","Развлечения","Подписки","Образование","Прочее"],
 income:["Зарплата","Фриланс","Бонус","Подарок","Инвестиции","Прочий доход"],
 transfer:["Перевод"]
};
const seed = {
 theme:"light",baseCurrency:"TJS",paydays:[{name:"Основная зарплата",date:25,amount:0,currency:"TJS"},{name:"Дополнительный доход",date:15,amount:0,currency:"TJS"}],
 wallets:[],
 transactions:[],
 budgets:[]
};
let state;
try { state = JSON.parse(localStorage.getItem("finora-state")) || structuredClone(seed); } catch { state = structuredClone(seed); }
if (!localStorage.getItem("finora-clean-start-v1")) { const isDemo = state.transactions?.some(t => ["t1","t2","t3","t4","t5"].includes(t.id)) || state.wallets?.some(w => ["cash","bank","usd"].includes(w.id)); if (isDemo) state = structuredClone(seed); localStorage.setItem("finora-state", JSON.stringify(state)); localStorage.setItem("finora-clean-start-v1","1"); }
let currentView = "dashboard", txType = "expense";
function save(){localStorage.setItem("finora-state",JSON.stringify(state)); if(window.FinoraCloud) window.FinoraCloud.queueSave(state);}
function wallet(id){return state.wallets.find(w=>w.id===id)||state.wallets[0]||{name:"Удалённый кошелёк",currency:"TJS"};}
function rate(currency){if(currency===state.baseCurrency)return 1; const rates={TJS:1,USD:10.9,EUR:11.9,RUB:.12};return rates[currency]/(rates[state.baseCurrency]||1);}
function convert(n,c){return n*rate(c);}
function txBase(t){return convert(t.amount,t.currency);}
function monthTx(){return state.transactions.filter(t=>t.date?.slice(0,7)===iso(today).slice(0,7));}
function expenses(list=monthTx()){return list.filter(t=>t.type==="expense").reduce((a,t)=>a+txBase(t),0);}
function incomes(list=monthTx()){return list.filter(t=>t.type==="income").reduce((a,t)=>a+txBase(t),0);}
function totalBalance(){return state.wallets.reduce((a,w)=>a+convert(w.balance,w.currency),0);}
function escapeHtml(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function dateLabel(d){return new Date(d+"T12:00:00").toLocaleDateString("ru-RU",{day:"numeric",month:"short"});}
function txIcon(t){return t.type==="income"?"↙":t.type==="transfer"?"⇄":({"Обед":"☕","Продукты":"◉","Транспорт":"↗","Дом":"⌂","Здоровье":"＋","Покупки":"◇","Развлечения":"♫"}[t.category]||"↗");}
function transactionHtml(t){const w=wallet(t.walletId);const sign=t.type==="income"?"+":t.type==="expense"?"−":"↔";const label=t.type==="transfer"?"Перевод":t.category;return `<div class="transaction"><div class="wallet-icon">${txIcon(t)}</div><div class="tx-info"><div class="tx-title">${escapeHtml(t.note||label)}</div><div class="tx-sub">${escapeHtml(label)} · ${escapeHtml(w.name)} · ${dateLabel(t.date)}</div></div><div class="tx-amount ${t.type==="income"?"positive":t.type==="expense"?"negative":""}">${sign}${fmt(t.amount,t.currency)}<small>${escapeHtml(t.currency)}</small></div></div>`;}
function totalMonthlyDays(){return new Date(today.getFullYear(),today.getMonth()+1,0).getDate();}
function monthRemainingDays(){return Math.max(1,totalMonthlyDays()-today.getDate()+1);}
function nextIncomeDate(){const future=state.paydays.map(p=>{let d=new Date(today.getFullYear(),today.getMonth(),Math.min(p.date,totalMonthlyDays()));if(d<new Date(today.getFullYear(),today.getMonth(),today.getDate()))d=new Date(today.getFullYear(),today.getMonth()+1,Math.min(p.date,new Date(today.getFullYear(),today.getMonth()+2,0).getDate()));return { ...p,when:d};}).sort((a,b)=>a.when-b.when);return future[0]||null;}
function renderDashboard(){
 const mt=monthTx(),spent=expenses(mt),earned=incomes(mt),bal=totalBalance(),days=monthRemainingDays();
 const regular=state.transactions.filter(t=>t.type==="expense"&&t.recurring).reduce((a,t)=>a+txBase(t),0);
 const next=nextIncomeDate(),daysPay=next?Math.max(0,Math.ceil((next.when-new Date(today.getFullYear(),today.getMonth(),today.getDate()))/86400000)):null;
 const avg=spent/Math.max(1,today.getDate()),reserved=regular,available=bal-reserved,dayLimit=Math.max(0,available/Math.max(1,daysPay??days));
 const projected=bal-(avg*Math.max(0,daysPay??days))+state.paydays.filter(p=>p.amount>0).reduce((a,p)=>a+convert(p.amount,p.currency),0);
 const byCat=categories.expense.map(c=>({name:c,value:mt.filter(t=>t.type==="expense"&&t.category===c).reduce((a,t)=>a+txBase(t),0)})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value).slice(0,5);
 const maxCat=Math.max(1,...byCat.map(x=>x.value));
 const bars=Array.from({length:6},(_,i)=>{const d=new Date(today.getFullYear(),today.getMonth()-5+i,1);const key=iso(d).slice(0,7);const v=state.transactions.filter(t=>t.type==="expense"&&t.date.slice(0,7)===key).reduce((a,t)=>a+txBase(t),0);return {label:d.toLocaleDateString("ru-RU",{month:"short"}).replace(".",""),value:v};});
 const maxBar=Math.max(1,...bars.map(b=>b.value));
 return `<div class="grid metrics">
 <div class="card"><div class="metric-label">Общий баланс <span class="metric-icon">▣</span></div><div class="metric-value">${fmt(bal)}</div><div class="metric-foot">Все кошельки · пересчёт в ${state.baseCurrency}</div></div>
 <div class="card"><div class="metric-label">Доходы за месяц <span class="metric-icon">↙</span></div><div class="metric-value positive">${fmt(earned)}</div><div class="metric-foot">Получено с начала месяца</div></div>
 <div class="card"><div class="metric-label">Расходы за месяц <span class="metric-icon">↗</span></div><div class="metric-value negative">${fmt(spent)}</div><div class="metric-foot">Среднее ${fmt(avg)} в день</div></div>
 <div class="card"><div class="metric-label">Доступно в день <span class="metric-icon">◷</span></div><div class="metric-value">${fmt(dayLimit)}</div><div class="metric-foot">${daysPay===null?"До конца месяца":`До ближайшего дохода: ${daysPay} дн.`}</div></div>
 </div>
 <div class="grid two-col">
  <div class="card"><div class="section-head"><h2>Расходы по месяцам</h2><span class="pill">6 месяцев</span></div><div class="chart-bars">${bars.map(b=>`<div class="bar-group"><div class="bar" style="height:${Math.max(3,b.value/maxBar*100)}%"></div><div class="bar-label">${escapeHtml(b.label)}</div></div>`).join("")}</div><div class="metric-foot">График на основе сохранённых операций.</div></div>
  <div class="card forecast"><div class="eyebrow">ПРОГНОЗ ДО БЛИЖАЙШЕГО ДОХОДА</div><h2>${fmt(Math.max(0,available-avg*(daysPay??days)))}</h2><div class="metric-foot">Ориентировочный остаток при текущем темпе расходов</div><div class="forecast-grid"><div><small>Следующее поступление</small><strong>${next?dateLabel(iso(next.when)):"Не задано"}</strong></div><div><small>Средний расход в день</small><strong>${fmt(avg)}</strong></div></div><div class="progress" style="margin-top:20px"><span style="width:${Math.min(100,Math.max(0,(available/Math.max(1,bal))*100))}%"></span></div><div class="metric-foot">Прогноз условный: настрой источники дохода и регулярные платежи для точности.</div></div>
 </div>
 <div class="grid two-col">
  <div class="card"><div class="section-head"><h2>Последние операции</h2><button class="text-btn" data-goto="transactions">Все операции →</button></div><div class="transactions">${[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(transactionHtml).join("")||'<div class="empty">Операций пока нет</div>'}</div></div>
  <div class="card"><div class="section-head"><h2>Кошельки</h2><button class="text-btn" data-goto="wallets">Все →</button></div>${state.wallets.slice(0,4).map(w=>`<div class="balance-row"><div class="wallet-left"><div class="wallet-icon">${escapeHtml(w.icon||"▣")}</div><div><div class="wallet-name">${escapeHtml(w.name)}</div><div class="wallet-sub">${escapeHtml(w.type)} · ${w.currency}</div></div></div><div class="wallet-amount">${fmt(w.balance,w.currency)}</div></div>`).join("")||'<div class="empty">Добавь первый кошелёк в разделе «Кошельки»</div>'}</div>
 </div>
 <div class="card"><div class="section-head"><h2>Бюджеты категорий</h2><button class="text-btn" data-goto="budgets">Управление →</button></div>${state.budgets.slice(0,4).map(b=>{const used=monthTx().filter(t=>t.type==="expense"&&t.category===b.category).reduce((a,t)=>a+txBase(t),0),p=used/Math.max(1,convert(b.limit,b.currency))*100;return `<div class="budget-item"><div class="budget-meta"><span>${escapeHtml(b.category)}</span><strong>${fmt(used)} <small>/ ${fmt(convert(b.limit,b.currency))}</small></strong></div><div class="progress"><span style="width:${Math.min(100,p)}%;background:${p>=100?"var(--red)":"var(--blue)"}"></span></div><div class="metric-foot">${Math.round(p)}% бюджета использовано</div></div>`}).join("")||'<div class="empty">Добавь бюджеты, чтобы контролировать лимиты.</div>'}
 </div>`;
}
function renderTransactions(){const list=[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date));return `<div class="notice"><strong>Быстрый ввод:</strong> нажми «Добавить» вверху, чтобы записать расход, доход или перевод.</div><div class="card"><div class="section-head"><h2>История операций</h2><span class="pill">${list.length} записей</span></div>${list.length?`<div class="transactions">${list.map(t=>transactionHtml(t)+`<div style="text-align:right;margin-top:-7px;margin-bottom:7px"><button class="text-btn" data-delete="${t.id}">Удалить</button></div>`).join("")}</div>`:'<div class="empty">Пока нет операций. Добавь первую запись.</div>'}</div>`;}
function renderWallets(){return `<p class="page-intro">Наличные, банковские карты и электронные кошельки в разных валютах.</p><div class="grid page-grid">${state.wallets.map(w=>`<div class="card"><div class="section-head"><div class="wallet-left"><div class="wallet-icon">${escapeHtml(w.icon||"▣")}</div><div><h2>${escapeHtml(w.name)}</h2><div class="wallet-sub">${escapeHtml(w.type)} · ${w.currency}</div></div></div><button class="text-btn" data-delete-wallet="${w.id}">Удалить</button></div><div class="metric-value">${fmt(w.balance,w.currency)}</div><div class="metric-foot">В пересчёте: ${fmt(convert(w.balance,w.currency))}</div></div>`).join("")}<div class="card"><div class="section-head"><h2>Новый кошелёк</h2><span class="metric-icon">＋</span></div><form id="walletForm"><label class="modal-label">Название<input name="name" required placeholder="Например, карта банка"></label><div class="form-grid"><label>Тип<select name="type"><option value="bank">Банковский</option><option value="cash">Наличные</option><option value="electronic">Электронный</option><option value="savings">Накопительный</option></select></label><label>Валюта<select name="currency">${currencies.map(c=>`<option>${c}</option>`).join("")}</select></label><label>Начальный баланс<input name="balance" type="number" step=".01" value="0" required></label></div><button class="primary-btn" type="submit">＋ Добавить кошелёк</button></form></div></div>`;}
function renderBudgets(){return `<p class="page-intro">Установи месячные лимиты и следи, какие категории приближаются к пределу.</p><div class="grid two-col"><div class="card"><div class="section-head"><h2>Использование бюджета</h2></div>${state.budgets.map(b=>{const used=monthTx().filter(t=>t.type==="expense"&&t.category===b.category).reduce((a,t)=>a+txBase(t),0),lim=convert(b.limit,b.currency),p=used/Math.max(1,lim)*100;return `<div class="budget-item"><div class="budget-meta"><span>${escapeHtml(b.category)}</span><strong>${fmt(used)} / ${fmt(lim)}</strong></div><div class="progress"><span style="width:${Math.min(100,p)}%;background:${p>=100?"var(--red)":"var(--blue)"}"></span></div><div class="metric-foot">${p>=100?"Лимит превышен":`Осталось ${fmt(Math.max(0,lim-used))}`} · ${Math.round(p)}%</div></div>`}).join("")||'<div class="empty">Бюджеты ещё не добавлены.</div>'}</div><div class="card"><div class="section-head"><h2>Создать бюджет</h2></div><form id="budgetForm"><label>Категория<select name="category">${categories.expense.map(c=>`<option>${c}</option>`).join("")}</select></label><div class="form-grid"><label>Лимит<input name="limit" type="number" min="1" step=".01" required placeholder="1000"></label><label>Валюта<select name="currency">${currencies.map(c=>`<option>${c}</option>`).join("")}</select></label></div><button class="primary-btn">Сохранить лимит</button></form><div class="section-head" style="margin-top:28px"><h2>Источники дохода</h2></div><p class="metric-foot">Задай ожидаемые поступления для прогноза до зарплаты.</p><form id="paydayForm">${state.paydays.map((p,i)=>`<div class="settings-row"><div style="flex:1"><b>${escapeHtml(p.name)}</b><p>День месяца <input name="day${i}" type="number" min="1" max="31" value="${p.date}" style="width:62px;background:var(--panel2);border:1px solid var(--line);border-radius:7px;padding:5px;color:var(--text)"></p><p>Сумма <input name="amount${i}" type="number" min="0" step=".01" value="${p.amount}" style="width:110px;background:var(--panel2);border:1px solid var(--line);border-radius:7px;padding:5px;color:var(--text)"> <select name="currency${i}" style="padding:5px">${currencies.map(c=>`<option ${c===p.currency?"selected":""}>${c}</option>`).join("")}</select></p></div></div>`).join("")}<button class="primary-btn" style="margin-top:12px">Сохранить поступления</button></form></div></div>`;}
function renderAnalytics(){const mt=monthTx(),total=expenses(mt),cats=categories.expense.map(c=>({name:c,value:mt.filter(t=>t.type==="expense"&&t.category===c).reduce((a,t)=>a+txBase(t),0)})).filter(c=>c.value>0).sort((a,b)=>b.value-a.value);const max=Math.max(1,...cats.map(c=>c.value));const days=Math.max(1,today.getDate());const lunches=mt.filter(t=>t.type==="expense"&&t.category==="Обед");const lunchTotal=lunches.reduce((a,t)=>a+txBase(t),0);return `<p class="page-intro">Сводка помогает увидеть, куда уходят деньги. Курсы валют в прототипе демонстрационные.</p><div class="grid metrics"><div class="card"><div class="metric-label">Расходы за месяц</div><div class="metric-value negative">${fmt(total)}</div><div class="metric-foot">${mt.filter(t=>t.type==="expense").length} операций</div></div><div class="card"><div class="metric-label">Средний расход в день</div><div class="metric-value">${fmt(total/days)}</div><div class="metric-foot">С начала месяца</div></div><div class="card"><div class="metric-label">На обеды</div><div class="metric-value">${fmt(lunchTotal)}</div><div class="metric-foot">${lunches.length} записей · ${fmt(lunchTotal/Math.max(1,lunches.length))} за обед</div></div><div class="card"><div class="metric-label">Доходы минус расходы</div><div class="metric-value ${(incomes(mt)-total)>=0?"positive":"negative"}">${fmt(incomes(mt)-total)}</div><div class="metric-foot">Денежный поток за месяц</div></div></div><div class="card"><div class="section-head"><h2>Расходы по категориям</h2><span class="pill">Текущий месяц</span></div>${cats.length?cats.map(c=>`<div class="budget-item"><div class="budget-meta"><span class="category-row"><span class="category-dot"></span>${escapeHtml(c.name)}</span><strong>${fmt(c.value)} <small>${Math.round(c.value/Math.max(1,total)*100)}%</small></strong></div><div class="progress"><span style="width:${c.value/max*100}%"></span></div></div>`).join(""):'<div class="empty">Добавь расходы, чтобы увидеть структуру трат.</div>'}</div><div class="card" style="margin-top:16px"><div class="section-head"><h2>Баланс по валютам</h2></div>${currencies.map(c=>{const n=state.wallets.filter(w=>w.currency===c).reduce((a,w)=>a+w.balance,0);return n?`<div class="balance-row"><div class="wallet-left"><div class="wallet-icon">${c==="TJS"?"Ѕ":c==="USD"?"$":c==="EUR"?"€":"₽"}</div><div class="wallet-name">${c}</div></div><div class="wallet-amount">${fmt(n,c)}<div class="wallet-sub">≈ ${fmt(convert(n,c))}</div></div></div>`:""}).join("")}</div>`;}
function renderSettings(){return `<p class="page-intro">Настройки и управление аккаунтом.</p><div class="card"><div class="settings-row"><div><b>Тема оформления</b><p>Светлая или тёмная</p></div><select id="themeSelect"><option value="light" ${state.theme==="light"?"selected":""}>Светлая</option><option value="dark" ${state.theme==="dark"?"selected":""}>Тёмная</option></select></div><div class="settings-row"><div><b>Основная валюта</b><p>Для сводных сумм и графиков</p></div><select id="baseCurrency">${currencies.map(c=>`<option ${state.baseCurrency===c?"selected":""}>${c}</option>`).join("")}</select></div></div>
 <div class="card" style="margin-top:16px"><div class="section-head"><h2>Аккаунт Finora</h2><span class="pill" id="cloudStatus">Проверка…</span></div><p class="metric-foot" id="cloudHint" style="margin-bottom:16px">Создай аккаунт или войди, чтобы хранить данные в облаке.</p><form id="cloudAuthForm"><label>Email<input id="cloudEmail" type="email" autocomplete="email" required placeholder="you@example.com"></label><label>Пароль<input id="cloudPassword" type="password" minlength="8" autocomplete="current-password" required placeholder="Не менее 8 символов"></label><div class="modal-actions" style="justify-content:flex-start"><button class="primary-btn" type="submit" id="cloudLogin">Войти</button><button class="secondary-btn" type="button" id="cloudSignup">Регистрация</button><button class="secondary-btn" type="button" id="cloudLogout" hidden>Выйти</button></div></form><div class="modal-actions" style="justify-content:flex-start;margin-top:14px"><button class="secondary-btn" type="button" id="cloudPull">Загрузить из облака</button><button class="secondary-btn" type="button" id="cloudPush">Сохранить в облако</button></div></div>`;}
const views={dashboard:renderDashboard,transactions:renderTransactions,wallets:renderWallets,budgets:renderBudgets,analytics:renderAnalytics,settings:renderSettings};
const titles={dashboard:"Обзор",transactions:"Операции",wallets:"Кошельки",budgets:"Бюджеты",analytics:"Аналитика",settings:"Настройки"};
function render(){document.documentElement.dataset.theme=state.theme;$("#pageTitle").textContent=titles[currentView];$("#todayLabel").textContent=today.toLocaleDateString("ru-RU",{weekday:"long",day:"numeric",month:"long"}).toUpperCase();$("#viewRoot").innerHTML=views[currentView]();$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===currentView));bindView();}
function goto(v){currentView=v;render();window.scrollTo({top:0,behavior:"smooth"});}
function toast(s){const el=$("#toast");el.textContent=s;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2300);}
function openModal(){populateWalletSelects();$("#date").value=iso(today);$("#amount").value="";$("#note").value="";$("#recurring").checked=false;$("#currency").value=state.baseCurrency;setType("expense");$("#modalBackdrop").hidden=false;setTimeout(()=>$("#amount").focus(),50);}
function closeModal(){$("#modalBackdrop").hidden=true;}
function populateWalletSelects(){const opts=state.wallets.map(w=>`<option value="${w.id}">${escapeHtml(w.name)} (${w.currency})</option>`).join("");$("#wallet").innerHTML=opts;$("#toWallet").innerHTML=opts;$("#category").innerHTML=categories[txType].map(c=>`<option>${c}</option>`).join("");}
function setType(type){txType=type;$$('#typeSegments button').forEach(b=>b.classList.toggle("selected",b.dataset.type===type));$("#categoryWrap").hidden=type==="transfer";$("#toWalletWrap").hidden=type!=="transfer";$("#category").innerHTML=categories[type].map(c=>`<option>${c}</option>`).join("");}
function bindView(){
 $$("[data-goto]").forEach(b=>b.onclick=()=>goto(b.dataset.goto));
 $$("[data-delete]").forEach(b=>b.onclick=()=>{const t=state.transactions.find(x=>x.id===b.dataset.delete);if(!t)return;if(confirm("Удалить эту операцию? Баланс кошелька будет пересчитан.")){const w=state.wallets.find(x=>x.id===t.walletId);if(w&&t.type==="expense")w.balance+=t.amount;if(w&&t.type==="income")w.balance-=t.amount;if(w&&t.type==="transfer"){w.balance+=t.amount;const dest=state.wallets.find(x=>x.id===t.toWalletId);if(dest)dest.balance-=t.amount;}state.transactions=state.transactions.filter(x=>x.id!==t.id);save();render();toast("Операция удалена, баланс восстановлен");}});
 $$("[data-delete-wallet]").forEach(b=>b.onclick=()=>{const id=b.dataset.deleteWallet;if(state.transactions.some(t=>t.walletId===id))return toast("Нельзя удалить кошелёк с историей операций");if(confirm("Удалить кошелёк?")){state.wallets=state.wallets.filter(w=>w.id!==id);save();render();}});
 const wf=$("#walletForm");if(wf)wf.onsubmit=e=>{e.preventDefault();const f=new FormData(wf);state.wallets.push({id:crypto.randomUUID(),name:f.get("name").trim(),type:f.get("type"),currency:f.get("currency"),balance:Number(f.get("balance")),icon:f.get("type")==="cash"?"◉":f.get("type")==="electronic"?"＄":"▣"});save();render();toast("Кошелёк добавлен");};
 const bf=$("#budgetForm");if(bf)bf.onsubmit=e=>{e.preventDefault();const f=new FormData(bf);const b={category:f.get("category"),limit:Number(f.get("limit")),currency:f.get("currency")};const old=state.budgets.find(x=>x.category===b.category);if(old)Object.assign(old,b);else state.budgets.push(b);save();render();toast("Бюджет сохранён");};
 const pf=$("#paydayForm");if(pf)pf.onsubmit=e=>{e.preventDefault();const f=new FormData(pf);state.paydays=state.paydays.map((p,i)=>({...p,date:Math.max(1,Math.min(31,Number(f.get("day"+i)||p.date))),amount:Math.max(0,Number(f.get("amount"+i)||0)),currency:f.get("currency"+i)||p.currency}));save();render();toast("Ожидаемые доходы сохранены");};
 const ts=$("#themeSelect");if(ts)ts.onchange=()=>{state.theme=ts.value;save();render();};
 const bc=$("#baseCurrency");if(bc)bc.onchange=()=>{state.baseCurrency=bc.value;save();render();};
 const cloudStatus=$("#cloudStatus"); if(cloudStatus && window.FinoraCloud){const cs=window.FinoraCloud.status();cloudStatus.textContent=cs.label;$("#cloudHint").textContent=cs.hint;const logout=$("#cloudLogout");if(logout)logout.hidden=!cs.signedIn;const login=$("#cloudLogin");if(login)login.disabled=!cs.configured;const signup=$("#cloudSignup");if(signup)signup.disabled=!cs.configured;}
 const authForm=$("#cloudAuthForm");if(authForm)authForm.onsubmit=async e=>{e.preventDefault();try{await window.FinoraCloud.signIn($("#cloudEmail").value,$("#cloudPassword").value);const remote=await window.FinoraCloud.pullState();state=remote||structuredClone(seed);localStorage.setItem("finora-state",JSON.stringify(state));save();render();toast(remote?"Вход выполнен, данные загружены":"Вход выполнен. Добавь первую операцию");}catch(err){toast("Ошибка входа: "+(err.message||"проверь настройки"));}};
 const signup=$("#cloudSignup");if(signup)signup.onclick=async()=>{try{const result=await window.FinoraCloud.signUp($("#cloudEmail").value,$("#cloudPassword").value);if(result.session){const remote=await window.FinoraCloud.pullState();state=remote||structuredClone(seed);localStorage.setItem("finora-state",JSON.stringify(state));save();}render();toast(result.session?"Аккаунт создан и вход выполнен":"Аккаунт создан. Теперь войди");}catch(err){toast("Ошибка регистрации: "+(err.message||"проверь настройки"));}};
 const logout=$("#cloudLogout");if(logout)logout.onclick=async()=>{try{await window.FinoraCloud.signOut();state=structuredClone(seed);localStorage.setItem("finora-state",JSON.stringify(state));render();toast("Выход выполнен");}catch(err){toast("Ошибка выхода");}};
 const pull=$("#cloudPull");if(pull)pull.onclick=async()=>{try{if(!confirm("Заменить локальные данные данными из облака? Сначала сделай экспорт, если он нужен."))return;const remote=await window.FinoraCloud.pullState();if(!remote){toast("В облаке пока нет сохранённых данных");return;}state=remote;localStorage.setItem("finora-state",JSON.stringify(state));render();toast("Данные загружены из облака");}catch(err){toast("Не удалось загрузить: "+(err.message||"проверь вход и схему БД"));}};
 const push=$("#cloudPush");if(push)push.onclick=async()=>{try{await window.FinoraCloud.pushNow(state);toast("Данные сохранены в облаке");}catch(err){toast("Не удалось сохранить: "+(err.message||"проверь вход и схему БД"));}};
}
$("#sideNav").addEventListener("click",e=>{const b=e.target.closest("[data-view]");if(b)goto(b.dataset.view);});
$("#quickAdd").onclick=openModal;$("#closeModal").onclick=closeModal;$("#cancelModal").onclick=closeModal;$("#modalBackdrop").addEventListener("click",e=>{if(e.target===$("#modalBackdrop"))closeModal();});
$("#themeToggle").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";save();render();};
$("#typeSegments").addEventListener("click",e=>{const b=e.target.closest("[data-type]");if(b){setType(b.dataset.type);populateWalletSelects();}});
$("#wallet").addEventListener("change",()=>{const w=wallet($("#wallet").value);if(w?.currency)$("#currency").value=w.currency;});
$("#currency").addEventListener("change",()=>{const match=state.wallets.find(w=>w.currency===$("#currency").value);if(match)$("#wallet").value=match.id;else toast("Сначала создай кошелёк в этой валюте");});
$("#transactionForm").onsubmit=e=>{e.preventDefault();const amount=Number($("#amount").value),currency=$("#currency").value,walletId=$("#wallet").value,date=$("#date").value,note=$("#note").value.trim(),recurring=$("#recurring").checked;if(!amount||amount<=0||!walletId||!date)return toast("Проверь сумму, кошелёк и дату");const from=wallet(walletId);if(currency!==from.currency)return toast("Валюта операции должна совпадать с валютой кошелька");if(txType==="transfer"){const toId=$("#toWallet").value;if(!toId||toId===walletId)return toast("Выбери другой кошелёк для перевода");const to=wallet(toId);if(from.currency!==to.currency)return toast("В демо перевод между разными валютами не поддерживается");if(from.balance<amount)return toast("Внимание: баланс кошелька станет отрицательным");from.balance-=amount;to.balance+=amount;state.transactions.push({id:crypto.randomUUID(),type:"transfer",amount,currency:from.currency,category:"Перевод",walletId,date,note:note||`В ${to.name}`,recurring:false,toWalletId:toId});}else{if(txType==="expense")from.balance-=amount;else from.balance+=amount;state.transactions.push({id:crypto.randomUUID(),type:txType,amount,currency,category:$("#category").value,walletId,date,note,recurring});}save();closeModal();render();toast(txType==="income"?"Доход сохранён":txType==="transfer"?"Перевод выполнен":"Расход сохранён");};
if("serviceWorker" in navigator && location.protocol!=="file:"){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));}
render();
if(window.FinoraCloud) window.FinoraCloud.init().then(()=>{if(currentView==="settings")render();}).catch(()=>{});
